kind: ConfigMap
apiVersion: v1
metadata:
  name: app-as3
  namespace: f5-test001
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.18.0",
        "id": "123abc",
        "label": "f5_test001",
        "remark": "HTTP application",
        "f5_test001": {
          "class": "Tenant",
          "f5_test001": {
            "class": "Application",
            "template": "generic",
            "app_svc_vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "10.1.10.60"
              ],
              "virtualPort": 80,
              "pool": "app_svc_pool"
            },
            "app_svc_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }