kind: ConfigMap
apiVersion: v1
metadata:
  name: cistest100
  namespace: cistest
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.19.0",
        "id": "cistest100",
        "cistest": {
          "class": "Tenant",
          "cistest_app-svc-1": {
            "class": "Application",
            "template": "generic",
            "app_svc_vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "10.1.10.3"
              ],
              "virtualPort": 80,
              "pool": "cistest_app-svc-1_pool"
            },
            "cistest_app-svc-1_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "members": [
              {
                "servicePort": 8080,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }